# Generated by Django 4.1.7 on 2023-03-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='computers',
            new_name='computer',
        ),
        migrations.RenameModel(
            old_name='jhumkas',
            new_name='jumkas',
        ),
    ]
